version: '3'
services:
#===============================================================================
# Database
#===============================================================================
  postgres:
    image: postgres:alpine
    expose:
      - '5432'
    volumes:
      - ${PERSISTENT_PATH}/data/postgres/${POSTGRES_DB}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
  db_backup:
    image: equinoxone/postgres_backup:0.1
    depends_on:
      - postgres
    volumes:
      - ${PERSISTENT_PATH}/backup:/backup
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - '5050:5050'

#===============================================================================
# API
#===============================================================================
  app:
    build: .
    command: bash -c "bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
#===============================================================================
# Networks
#===============================================================================
  nginx:
    image: nginx
    depends_on:
      - app
    volumes:
      - ${PERSISTENT_PATH}/logs/nginx:/var/log/nginx
