version: '3'
services:
  app:
    build: ./app
    volumes:
      - ./:/app
      - ./public/uploads/:/app/public/uploads/
      - ./tmp:/app/tmp
      - ./log:/app/log
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.devel.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  db_backup:
    command: /bin/true
