version: '3'
services:
#===============================================================================
# API
#===============================================================================
  rails:
    build: ./rails
    command:
      bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ${API_SRC_PATH}:/rails
      - ${PERSISTENT_PATH}/rails/usr/local/bundle:/usr/local/bundle
      - ${PERSISTENT_PATH}/rails/app/tmp:/app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - internal

#===============================================================================
# Database
#===============================================================================
  postgres:
    image: postgres:alpine
    expose:
      - '5432'
    volumes:
      - ${PERSISTENT_PATH}/data/postgres/${POSTGRES_DB}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    networks:
      - internal

#===============================================================================
# Networks
#===============================================================================
networks:
  internal:
    driver: 'bridge'
