source 'https://rubygems.org'
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end
ruby '2.4.1'
gem 'rails', '~> 5.0.2'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'rails_admin', '~> 1.2'
gem 'activerecord-postgis-adapter'
gem 'jwt'
gem 'koala'
gem 'rest-client'
gem 'apipie-rails'
gem 'ar-uuid' # http://nandovieira.com/using-uuid-with-postgresql-and-activerecord

group :development, :test do
  # Shim to load environment variables from .env into ENV in development.
  gem 'dotenv-rails' # https://github.com/bkeepers/dotenv
  gem 'byebug', platform: :mri
end
group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bootstrap', '~> 4.0.0.alpha6'
gem 'devise'
gem 'high_voltage'
gem 'pg'
group :development do
  gem 'better_errors'
  gem 'rails_layout'
end
